///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/FrisBot.aks
/// Generation time: mar oct 31 20:15:26 CET 2017
///

/// Song 'mainSong' metadata macros
#define mainSong_address  0x0100
#define mainSong_size     3583
#define mainSong_end      0xEFF

/// Song 'mainSong' array declaration
extern void mainSong[mainSong_size];
